export const projects = [
  {
    title: 'Library Management',
    description: "The Main Aim Of This Project Is To Develop A Backend Of A “Library Management, Here We Will Create APIs Where User Can Create User Document, Books Document. Further We Will Also Create A Get Api To Enlist All The Books With Filters Implemented Through Query. We Will Be Protecting Our Routes With Authentication And Authorization Using Jwt Tokens.",
      image: '/images/one.png',
      tags: ["NodeJs", "MongoDb", "JWT"],
    source: 'https://github.com/ajit-kerle/Book_Management_Project/tree/final_project',
    visit: 'https://drive.google.com/drive/folders/1FpxOf4kDoUk9XEgtFL1YfyZE6TyNmPEC?usp=share_link',
    id: 0,
  },
  {
    title: 'Open To Intern',
    description:"The Main Aim Of This Project Is To Develop A Backend Of Open To Intern Website, With The Help Of APIs, We Have Tried To Optimized The Time Of Req -Res Cycle. Also, With The Help Of Amazon S3 We Have Created Logo For Our College And We Have Used Axios.It Can Run In The Browser And Node.Js With The Same Codebase.",
    image: '/images/two.png',
    tags: ['AWS S3', 'Expressjs',"Nodejs"],
    source: 'https://github.com/ajit-kerle/Open-To-Intern-Project',
    visit: 'https://drive.google.com/drive/folders/1sRg51UsZ6RtfLAk7fsdmYpq85AfkCTS8?usp=share_link',
    id: 1,
  },
  {
    title: 'URL Shortner',
    description: "The main aim of URL shortening is used to create shorter aliases for long URLs. We call these shortened aliases “short links.” Users are redirected to the original URL when they hit these short links. Short links save a lot of space when displayed, printed, messaged, or tweeted.",
      image: '/images/short.png',
      tags: ['Redis', 'MongoDB',"Postman","Express"],
    source: 'https://github.com/ajit-kerle/Url-Shortner--project4/tree/project/urlShortnerGroup53',
    visit: 'https://drive.google.com/file/d/1PoPrTIqYadTPlTuTOSpess1fqGZ99Xis/view?usp=share_link',
    id: 2,
  },
  {
    title: 'Products Management',
    description: "The Aim Of This Project Is To Create A Clone Of Backend Architect Of Shopping Websites Like “Amazon”, “Flipkart” Etc.This project is divided into 4 features namely User, Product, Cart and Order.Authenticated user can add or delete order also implemented.User can upload Images and we are using aws to store docs.",
    image: '/images/four.png',
    tags: ['AWS S3', 'MongoDB', 'Nodejs',"JWT"],
    source: 'https://github.com/ajit-kerle/product-management/tree/newNew',
    visit: 'https://drive.google.com/file/d/11bEHZ_Mp-F8zelG56aUsPBeU1miMOBYY/view?usp=share_link',
    id: 3,
  },
  {
    title: "Bloging-site",
    description: "The aim of this project is to learn about crud operation and Authentication and authorization using JSON Web token.In this project user can create blog,update blog, delete blog and filter blog using some keywords.",
    image: '/images/five.png',
    tags: ['Javascript', 'MongoDB', 'Nodejs',"JWT"],
    source: 'https://github.com/ajit-kerle/product-https://github.com/ajit-kerle/Mini-Bloging-site-backend-project',
    visit: 'https://drive.google.com/drive/folders/1tuyMYEgPrFVs3MU5zt-XFTJ5xzbDI3WB?usp=share_link',
    id: 3,
  },
  {
    title: "Books-management",
    description: "The aim of this project is to learn about crud operation using latest and google develope programing language.In this project user can create, update,delete book.",
    image: '/images/six.png',
    tags: ["Golang","gin framework","Gorm"],
    source: 'https://github.com/ajit-kerle/GO-GIN-GORM-POSTGRESQL-BOOKMANAGEMENT',
    visit: 'https://github.com/ajit-kerle/GO-GIN-GORM-POSTGRESQL-BOOKMANAGEMENT',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my bachelors of computer science', },
  { year: 2019, text: 'Started Learning Blockchain technology', },
  { year: 2021, text: 'Started web developement in Python', },
  { year: 2022, text: 'Recently Graduate', },
  { year: 2022, text: 'Completed Coding Bootcamp',},
];